---
- name: Configurar IPv6 en Loopback33
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configurar interfaz Loopback33 IPv6
      ios_config:
        lines:
          - interface Loopback33
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local
          - no shutdown
